### ISSUE TITLE
Specify container of migrate pod to exec in

### ISSUE THREAD

**Issue by LittleFox94** [replicatedhq/pvmigrate#19]
When using this on my cluster, it crashed at one point because the migration pod additional containers from linkerd. Besides allowing to add annotations to the migration pod (#18), it would probably be good to specify the container to exec rsync in.

Error was the "you have to specify a container" one, which happens when doing a `kubectl exec $pod` on a pod with multiple containers without specifying the target container. I sadly don't have any logs saved ._.

I wrote two issues because it's two different problems, but I think this here is the root cause to fix in my setup, while the other (#18) might be important for other setups.

**Comment by laverya** [comment]
I think this is probably from where we're tailing the logs of the migration pod - easy enough to fix!

**Comment by laverya** [comment]
fix merged.

**Comment by LittleFox94** [comment]
oh that was fast, nice job :)

and thank you for this tool, did some of my PVCs by hand some months ago but procrastinated the others for quite some time now ... x)

**Comment by laverya** [comment]
Fixed in https://github.com/replicatedhq/pvmigrate/releases/tag/v0.3.2
