### ISSUE TITLE
Sending SIGINT while the tool checks for migration Pod readiness causes infinity loop

### ISSUE THREAD

**Issue by gregth** [replicatedhq/pvmigrate#216]
Currently, if the user sends a SIGINT (Ctrl+C) to the process while it is waiting for the migration Pod to become Ready, the process will enter an infinity loop, because method:

    1. It will try to get the Pod from the API Server
    2. The client will return an error because the context is expired (due to SIGINT).
    3. It will continue to the next iteration of the loop.

The body of the method `copyOnePVC()` should check if the context has expired and return in immediately an error to the caller, immediately so that the script exits immediately.

**Comment by gregth** [comment]
I've sent a quick fix for this, see PR https://github.com/replicatedhq/pvmigrate/issues/216. 

Feel free to suggest any other approaches that might be more sophisticated for fixing the issue.

**Comment by laverya** [comment]
Looks good to me, I'll merge your fix and get a release out

**Comment by laverya** [comment]
This is released as part of [v0.10.2](https://github.com/replicatedhq/pvmigrate/releases/tag/v0.10.2), thank you for the contribution!

**Comment by gregth** [comment]
Thanks @laverya !
