### ISSUE TITLE
Duplicate project

### ISSUE THREAD

**Issue by utkuozdemir** [replicatedhq/pvmigrate#45]
Hi there 👋 

Just wanted to let you know that I have been maintaining a project that does the same thing, and have (nearly) the same name:
https://github.com/utkuozdemir/pv-migrate

Cheers

**Comment by laverya** [comment]
Very similar indeed! I unfortunately only discovered the name collision after the fact 😬 

This project really should have been called 'scmigrate' (storageclass-migrate), in retrospect. (As the intent isn't to migrate one PV, but to migrate _every_ PV using a given Storage Class)

**Comment by utkuozdemir** [comment]
No worries, I just saw your project while submitting mine to krew and wanted to drop by :) Cool project btw :)

cheers

**Comment by laverya** [comment]
To be completely honest, "not knowing how to rename something in krew" is the major blocker for me renaming this...
