### ISSUE TITLE
Allow filtering by namespace

### ISSUE THREAD

**Issue by gozer** [replicatedhq/pvmigrate#69]
A --namespace option could be useful for testing and targeted migrations

@davidfluck, sounds fun ?

**Comment by laverya** [comment]
Makes sense to me!

And pretty easy to do, too - you could probably just drop it in https://github.com/replicatedhq/pvmigrate/blob/09fba6b10073cb1e5590079e716aaf0eac60876a/pkg/migrate/migrate.go#L402-L413
